package com.printkiosk.client._disabled;

import com.printkiosk.service.print.PrintManager;
import com.printkiosk.service.print.PrintService;
import com.printkiosk.service.print.PrintSettings;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.springframework.stereotype.Service;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

@Slf4j
@Service
@RequiredArgsConstructor
public class TestPrintService {

    private final PrintManager printManager;

    public PrintService.PrintResult printTestPage() {
        Path testPdfPath = null;

        try {
            testPdfPath = createTestPdf();

            PrintSettings settings = new PrintSettings(
                    1,
                    false,
                    false,
                    "PORTRAIT",
                    "A4"
            );

            PrintManager.PrintResult managerResult = printManager.printAndDeleteLocalFile(
                    testPdfPath.toAbsolutePath().toString(),
                    "application/pdf",
                    settings,
                    (progress, message) -> log.info("Test print progress: {} - {}", progress, message)
            );

            if (managerResult.success()) {
                return new PrintService.PrintResult(true, "Тестовая страница успешно отправлена на печать.");
            }

            return new PrintService.PrintResult(false, managerResult.errorMessage());

        } catch (Exception e) {
            log.error("Test print failed", e);

            if (testPdfPath != null) {
                try {
                    Files.deleteIfExists(testPdfPath);
                } catch (Exception deleteError) {
                    log.warn("Could not delete test PDF after failure: {}", testPdfPath, deleteError);
                }
            }

            return new PrintService.PrintResult(false, "Ошибка тестовой печати: " + e.getMessage());
        }
    }

    private Path createTestPdf() throws Exception {
        Path tempDir = Path.of(
                System.getProperty("user.home"),
                "Desktop",
                "KioskTempFiles",
                "test-print"
        );

        Files.createDirectories(tempDir);

        Path pdfPath = tempDir.resolve("print-kiosk-test-" + UUID.randomUUID() + ".pdf");

        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            PDType1Font titleFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font normalFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            try (PDPageContentStream content = new PDPageContentStream(document, page)) {
                float y = 760;

                content.beginText();
                content.setFont(titleFont, 26);
                content.newLineAtOffset(70, y);
                content.showText("Print Kiosk Test Page");
                content.endText();

                y -= 55;

                content.beginText();
                content.setFont(normalFont, 15);
                content.newLineAtOffset(70, y);
                content.showText("This page was generated by AlaToo Print Kiosk.");
                content.endText();

                y -= 35;

                content.beginText();
                content.setFont(normalFont, 15);
                content.newLineAtOffset(70, y);
                content.showText("Mode: Black & White");
                content.endText();

                y -= 30;

                content.beginText();
                content.setFont(normalFont, 15);
                content.newLineAtOffset(70, y);
                content.showText("Paper: A4");
                content.endText();

                y -= 30;

                content.beginText();
                content.setFont(normalFont, 15);
                content.newLineAtOffset(70, y);
                content.showText("Copies: 1");
                content.endText();

                y -= 30;

                content.beginText();
                content.setFont(normalFont, 15);
                content.newLineAtOffset(70, y);
                content.showText("Generated at: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
                content.endText();

                y -= 70;

                content.setLineWidth(1.5f);
                content.moveTo(70, y);
                content.lineTo(525, y);
                content.stroke();

                y -= 45;

                content.beginText();
                content.setFont(titleFont, 18);
                content.newLineAtOffset(70, y);
                content.showText("If you can read this page, the printer integration works.");
                content.endText();
            }

            document.save(pdfPath.toFile());
        }

        log.info("Test print PDF created: {}", pdfPath);

        return pdfPath;
    }
}
